# Generated by Django 2.2.1 on 2019-06-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190602_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='月次に関するコメント'),
        ),
    ]
